export default {
    page: 1,
    total_results: 401195,
    total_pages: 20060,
    results: [
        {
            vote_count: 1099,
            id: 450465,
            video: false,
            vote_average: 6.8,
            title: 'Glass',
            popularity: 346.191,
            poster_path: '/svIDTNUoajS8dLEo7EosxvyAsgJ.jpg',
            original_language: 'en',
            original_title: 'Glass',
            genre_ids: [
                53,
                9648,
                18,
            ],
            backdrop_path: '/lvjscO8wmpEbIfOEZi92Je8Ktlg.jpg',
            adult: false,
            overview: 'In a series of escalating encounters, security guard David Dunn uses his supernatural abilities to track Kevin Wendell Crumb, a disturbed man who has twenty-four personalities. Meanwhile, the shadowy presence of Elijah Price emerges as an orchestrator who holds secrets critical to both men.',
            release_date: '2019-01-16',
        },
        {
            vote_count: 4544,
            id: 424694,
            video: false,
            vote_average: 8.2,
            title: 'Bohemian Rhapsody',
            popularity: 265.819,
            poster_path: '/lHu1wtNaczFPGFDTrjCSzeLPTKN.jpg',
            original_language: 'en',
            original_title: 'Bohemian Rhapsody',
            genre_ids: [
                18,
                10402,
            ],
            backdrop_path: '/93xA62uLd5CwMOAs37eQ7vPc1iV.jpg',
            adult: false,
            overview: "Singer Freddie Mercury, guitarist Brian May, drummer Roger Taylor and bass guitarist John Deacon take the music world by storm when they form the rock 'n' roll band Queen in 1970. Hit songs become instant classics. When Mercury's increasingly wild lifestyle starts to spiral out of control, Queen soon faces its greatest challenge yet – finding a way to keep the band together amid the success and excess.",
            release_date: '2018-10-24',
        },
        {
            vote_count: 738,
            id: 428078,
            video: false,
            vote_average: 6,
            title: 'Mortal Engines',
            popularity: 262.19,
            poster_path: '/uXJVpPXxZO4L8Rz3IG1Y8XvZJcg.jpg',
            original_language: 'en',
            original_title: 'Mortal Engines',
            genre_ids: [
                878,
                28,
                12,
                14,
                53,
            ],
            backdrop_path: '/rxYG6Sj95as9rv9wKIHUx6ATWd3.jpg',
            adult: false,
            overview: 'Set in a world many thousands of years in the future. Earth’s cities now roam the globe on huge wheels, devouring each other in a struggle for ever diminishing resources. On one of these massive Traction Cities, Tom Natsworthy has an unexpected encounter with a mysterious young woman from the Outlands who will change the course of his life forever.',
            release_date: '2018-12-05',
        },
        {
            vote_count: 3344,
            id: 297802,
            video: false,
            vote_average: 6.8,
            title: 'Aquaman',
            popularity: 202.569,
            poster_path: '/5Kg76ldv7VxeX9YlcQXiowHgdX6.jpg',
            original_language: 'en',
            original_title: 'Aquaman',
            genre_ids: [
                28,
                14,
                878,
                12,
            ],
            backdrop_path: '/5A2bMlLfJrAfX9bqAibOL2gCruF.jpg',
            adult: false,
            overview: "Once home to the most advanced civilization on Earth, the city of Atlantis is now an underwater kingdom ruled by the power-hungry King Orm. With a vast army at his disposal, Orm plans to conquer the remaining oceanic people -- and then the surface world. Standing in his way is Aquaman, Orm's half-human, half-Atlantean brother and true heir to the throne. With help from royal counselor Vulko, Aquaman must retrieve the legendary Trident of Atlan and embrace his destiny as protector of the deep.",
            release_date: '2018-12-07',
        },
        {
            vote_count: 117,
            id: 522681,
            video: false,
            vote_average: 6.5,
            title: 'Escape Room',
            popularity: 188.446,
            poster_path: '/8yZAx7tlKRZIg7pJfaPhl00yHIQ.jpg',
            original_language: 'en',
            original_title: 'Escape Room',
            genre_ids: [
                27,
                53,
                28,
            ],
            backdrop_path: '/mWLljCmpqlcYQh7uh51BBMwCZwN.jpg',
            adult: false,
            overview: 'Six strangers find themselves in circumstances beyond their control, and must use their wits to survive.',
            release_date: '2019-01-03',
        },
        {
            vote_count: 961,
            id: 480530,
            video: false,
            vote_average: 6.6,
            title: 'Creed II',
            popularity: 170.777,
            poster_path: '/v3QyboWRoA4O9RbcsqH8tJMe8EB.jpg',
            original_language: 'en',
            original_title: 'Creed II',
            genre_ids: [
                18,
                28,
            ],
            backdrop_path: '/8yqLPNwNCtpOPc3XkOlkSMnghzw.jpg',
            adult: false,
            overview: "Follows Adonis Creed's life inside and outside of the ring as he deals with new found fame, issues with his family, and his continuing quest to become a champion.",
            release_date: '2018-11-21',
        },
        {
            vote_count: 19,
            id: 452832,
            video: false,
            vote_average: 4.9,
            title: 'Serenity',
            popularity: 149.024,
            poster_path: '/hgWAcic93phg4DOuQ8NrsgQWiqu.jpg',
            original_language: 'en',
            original_title: 'Serenity',
            genre_ids: [
                53,
                18,
            ],
            backdrop_path: '/oOROXoQ402tHgK6NowmMUSLffkW.jpg',
            adult: false,
            overview: 'Baker Dill is a fishing boat captain leading tours off a tranquil, tropical enclave called Plymouth Island. His quiet life is shattered, however, when his ex-wife Karen tracks him down with a desperate plea for help.',
            release_date: '2019-01-24',
        },
        {
            vote_count: 50,
            id: 505954,
            video: false,
            vote_average: 4.6,
            title: 'T-34',
            popularity: 146.519,
            poster_path: '/qNBjbjpQC2Rm8M1v0X8jQxb4AnN.jpg',
            original_language: 'ru',
            original_title: 'Т-34',
            genre_ids: [
                10752,
                18,
                12,
            ],
            backdrop_path: '/59qyrVGLLtrcuFtJGdixzn7H4OI.jpg',
            adult: false,
            overview: '1941 - WWii. the second lieutenant Nikolai ivushkin, commander of a t-34, engages in an unequal battle against the tank ace Klaus Jager in a battle near moscow. His mission is more of a suicide - to destroy a dozen german tanks, all by himself. that said, luck does favour the bold. He wins the battle, barely survives, but loses his tank and lands himself in captivity for three long years... there was little to no chance for ivushkin and Jager to meet again, but the war knows how to throw a curve ball.in the spring of 1944, the Wehrmacht commands Jager to take charge of the ohrdruf  re range and turn it into a training center for elite german armored forces, using the latest t-34 as a running target. this is how Jager and ivushkin cross paths again. Jager o ers ivushkin to become the commander of a legendary tank and pick his crew from fellow camp prisoners. Nothing goes according to plan, though, when ivushkin uses exercises for a daring and carefully planned escape.',
            release_date: '2018-12-27',
        },
        {
            vote_count: 1105,
            id: 424783,
            video: false,
            vote_average: 6.5,
            title: 'Bumblebee',
            popularity: 144.792,
            poster_path: '/fw02ONlDhrYjTSZV8XO6hhU3ds3.jpg',
            original_language: 'en',
            original_title: 'Bumblebee',
            genre_ids: [
                28,
                12,
                878,
            ],
            backdrop_path: '/hMANgfPHR1tRObNp2oPiOi9mMlz.jpg',
            adult: false,
            overview: 'On the run in the year 1987, Bumblebee finds refuge in a junkyard in a small Californian beach town. Charlie, on the cusp of turning 18 and trying to find her place in the world, discovers Bumblebee, battle-scarred and broken.  When Charlie revives him, she quickly learns this is no ordinary yellow VW bug.',
            release_date: '2018-12-15',
        },
        {
            vote_count: 238,
            id: 166428,
            video: false,
            vote_average: 8.1,
            title: 'How to Train Your Dragon: The Hidden World',
            popularity: 139.443,
            poster_path: '/ij0xoc13hGhrYIlXGGuPXWTh3vi.jpg',
            original_language: 'en',
            original_title: 'How to Train Your Dragon: The Hidden World',
            genre_ids: [
                16,
                10751,
                12,
            ],
            backdrop_path: '/c56qP2v5vDeYd6Kre9DL47VMcUH.jpg',
            adult: false,
            overview: 'As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away.  When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.',
            release_date: '2019-01-03',
        },
        {
            vote_count: 353,
            id: 504172,
            video: false,
            vote_average: 6.3,
            title: 'The Mule',
            popularity: 128.04,
            poster_path: '/t0idiLMalKMj2pLsvqHrOM4LPdQ.jpg',
            original_language: 'en',
            original_title: 'The Mule',
            genre_ids: [
                80,
                18,
                53,
            ],
            backdrop_path: '/bkc4AY6FTa3yNqrshE9b1elDzPt.jpg',
            adult: false,
            overview: 'A 90 year old horticulturalist and Korean War veteran is caught transporting $3 million worth of cocaine through Illinois for a Mexican drug cartel.',
            release_date: '2018-12-14',
        },
        {
            vote_count: 329,
            id: 483906,
            video: false,
            vote_average: 6.3,
            title: 'Polar',
            popularity: 125.587,
            poster_path: '/qOBEpKVLl8Q9CZScbOcRRVISezV.jpg',
            original_language: 'en',
            original_title: 'Polar',
            genre_ids: [
                28,
                80,
                35,
                18,
            ],
            backdrop_path: '/u8CP7EeWbYMlIVqEoKAt6OYsEe1.jpg',
            adult: false,
            overview: 'When a retiring assassin realizes that he is the target of a hit, he winds up back in the game going head to head with a gang of younger, ruthless killers.',
            release_date: '2019-01-25',
        },
        {
            vote_count: 479,
            id: 401469,
            video: false,
            vote_average: 6.7,
            title: 'Widows',
            popularity: 124.26,
            poster_path: '/tvmPiTShsfp4vSUBFsCHYaX9M7i.jpg',
            original_language: 'en',
            original_title: 'Widows',
            genre_ids: [
                80,
                18,
                53,
            ],
            backdrop_path: '/71OjxI27tK7kTIiPnMkdQDx14pe.jpg',
            adult: false,
            overview: "A police shootout leaves four thieves dead during an explosive armed robbery attempt in Chicago. Their widows have nothing in common except a debt left behind by their spouses' criminal activities. Hoping to forge a future on their own terms, they join forces to pull off a heist.",
            release_date: '2018-11-06',
        },
        {
            vote_count: 3299,
            id: 332562,
            video: false,
            vote_average: 7.4,
            title: 'A Star Is Born',
            popularity: 123.553,
            poster_path: '/wrFpXMNBRj2PBiN4Z5kix51XaIZ.jpg',
            original_language: 'en',
            original_title: 'A Star Is Born',
            genre_ids: [
                18,
                10402,
                10749,
            ],
            backdrop_path: '/wqtaHWOEZ3rXDJ8c6ZZShulbo18.jpg',
            adult: false,
            overview: "Seasoned musician Jackson Maine discovers — and falls in love with — struggling artist Ally. She has just about given up on her dream to make it big as a singer — until Jack coaxes her into the spotlight. But even as Ally's career takes off, the personal side of their relationship is breaking down, as Jack fights an ongoing battle with his own internal demons.",
            release_date: '2018-10-03',
        },
        {
            vote_count: 11197,
            id: 299536,
            video: false,
            vote_average: 8.3,
            title: 'Avengers: Infinity War',
            popularity: 109.814,
            poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
            original_language: 'en',
            original_title: 'Avengers: Infinity War',
            genre_ids: [
                12,
                28,
                14,
            ],
            backdrop_path: '/bOGkgRGdhrBYJSLpXaxhXVstddV.jpg',
            adult: false,
            overview: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality. Everything the Avengers have fought for has led up to this moment - the fate of Earth and existence itself has never been more uncertain.',
            release_date: '2018-04-25',
        },
        {
            vote_count: 210,
            id: 463684,
            video: false,
            vote_average: 5.8,
            title: 'Velvet Buzzsaw',
            popularity: 109.089,
            poster_path: '/3rViQPcrWthMNecp5XnkKev6BzW.jpg',
            original_language: 'en',
            original_title: 'Velvet Buzzsaw',
            genre_ids: [
                53,
                9648,
                27,
                35,
            ],
            backdrop_path: '/ckNp6LPhp1roR8dVI16q5u3LUMg.jpg',
            adult: false,
            overview: 'Big money artists and mega-collectors pay a high price when art collides with commerce. After a series of paintings by an unknown artist are discovered, a supernatural force enacts revenge on those who have allowed their greed to get in the way of art.',
            release_date: '2019-02-01',
        },
        {
            vote_count: 20,
            id: 454294,
            video: false,
            vote_average: 5.7,
            title: 'The Kid Who Would Be King',
            popularity: 108.596,
            poster_path: '/aWENxGrJmXmHvifG6x2aYnpovXI.jpg',
            original_language: 'en',
            original_title: 'The Kid Who Would Be King',
            genre_ids: [
                28,
                12,
                14,
                10751,
            ],
            backdrop_path: '/5NZdSaEPAByrbtFW7Rp2pUV7CU9.jpg',
            adult: false,
            overview: 'Alex thinks he’s just another nobody, until he stumbles upon the mythical Sword in the Stone, Excalibur. Now, he must unite his friends and enemies into a band of knights and, together with the legendary wizard Merlin, take on the wicked enchantress Morgana. With the future at stake, Alex must become the great leader he never dreamed he could be.',
            release_date: '2019-01-16',
        },
        {
            vote_count: 310,
            id: 438799,
            video: false,
            vote_average: 6.9,
            title: 'Overlord',
            popularity: 102.869,
            poster_path: '/l76Rgp32z2UxjULApxGXAPpYdAP.jpg',
            original_language: 'en',
            original_title: 'Overlord',
            genre_ids: [
                27,
                10752,
            ],
            backdrop_path: '/iEQgMiqCIzS1osIuafgctvluGj5.jpg',
            adult: false,
            overview: 'France, World War II, June 1944. On the eve of D-Day, some American paratroopers fall behind enemy lines after their plane crashes during a mission consisting of destroying a German radio tower in Cielblanc, a small village near the beaches of Normandy. After reaching their target, the surviving paratroopers realize that, in addition to fighting Nazi troops that patrol the village, they also must fight against something else.',
            release_date: '2018-11-01',
        },
        {
            vote_count: 1463,
            id: 324857,
            video: false,
            vote_average: 8.5,
            title: 'Spider-Man: Into the Spider-Verse',
            popularity: 101.293,
            poster_path: '/laMM4lpQSh5z6KIBPwWogkjzBVQ.jpg',
            original_language: 'en',
            original_title: 'Spider-Man: Into the Spider-Verse',
            genre_ids: [
                28,
                12,
                16,
                878,
                35,
            ],
            backdrop_path: '/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg',
            adult: false,
            overview: 'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
            release_date: '2018-12-07',
        },
        {
            vote_count: 147,
            id: 567860,
            video: false,
            vote_average: 7,
            title: 'Fyre',
            popularity: 96.992,
            poster_path: '/yFsP0BAJhAH3RTXCAnGvI1CtaUb.jpg',
            original_language: 'en',
            original_title: 'Fyre',
            genre_ids: [
                99,
            ],
            backdrop_path: '/rBnUusNA6FmypqjGmRo5dvgycqL.jpg',
            adult: false,
            overview: 'He promised supermodels and yachts, but delivered tents and cheese sandwiches. How one man engineered a music festival disaster.',
            release_date: '2019-01-18',
        },
    ],
};
